### ISSUE TITLE
Push notification stops when there is an error

### ISSUE THREAD

**Issue by bNobo** [bNobo/wind-forecast-api#1]
mai 04 06:13:49 raspberrypi windforecast-api[7292]: fail: wind_forecast_api.Services.PushNotificationsProducer[0]
mai 04 06:13:49 raspberrypi windforecast-api[7292]:       Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: U. Path '', line 0, position 0.
mai 04 06:13:49 raspberrypi windforecast-api[7292]:          at Newtonsoft.Json.JsonTextReader.ParseValue()
mai 04 06:13:49 raspberrypi windforecast-api[7292]:          at Newtonsoft.Json.JsonTextReader.Read()
mai 04 06:13:49 raspberrypi windforecast-api[7292]:          at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
mai 04 06:13:49 raspberrypi windforecast-api[7292]:          at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
mai 04 06:13:49 raspberrypi windforecast-api[7292]:          at wind_forecast_api.Services.PushNotificationsProducer.ExecuteInternalAsync(CancellationToken stoppingToken) in C:\Users\benoi\source\repos\wind-forecast-api\Services\PushNotificationsProducer.cs:line 74
mai 04 06:13:49 raspberrypi windforecast-api[7292]:          at wind_forecast_api.Services.PushNotificationsProducer.ExecuteAsync(CancellationToken stoppingToken) in C:\Users\benoi\source\repos\wind-forecast-api\Services\PushNotificationsProducer.cs:line 51

**Comment by bNobo** [comment]
Added infinite catch and retry after 30s delay.
